services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  scraper:
    build: ./scraper
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongo:27017
    restart: "no"

#   app:
#     build: ./app
#     ports:
#       - "8501:8501"
#     depends_on:
#       - mongodb
#     environment:
#       - MONGO_URI=mongodb://mongo:27017

# volumes:
#   mongo_data:
